name: Linting

on:
  push:
    branches:
      - main
      - master
      - dev
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  hacs: # https://github.com/hacs/action
    name: "HACS Validation"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v3.5.2"

      - name: "Run HACS validation"
        uses: "hacs/action@main"
        with:
          category: "integration"
          # Remove this 'ignore' key when you have added brand images for your integration to https://github.com/home-assistant/brands
          ignore: "brands"

  hassfest: # https://developers.home-assistant.io/blog/2020/04/16/hassfest
    name: "Hassfest Validation"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v3.5.2"

      - name: "Run hassfest validation"
        uses: "home-assistant/actions/hassfest@master"

  # tests:
  #   runs-on: "ubuntu-latest"
  #   name: Run tests
  #   steps:
  #     - name: Check out code from GitHub
  #       uses: "actions/checkout@v2.3.4"
  #     - name: Setup Python ${{ env.DEFAULT_PYTHON }}
  #       uses: "actions/setup-python@v2.2.1"
  #       with:
  #         python-version: ${{ env.DEFAULT_PYTHON }}
  #     - name: Install requirements
  #       run: |
  #         pip install --constraint=.github/workflows/constraints.txt pip
  #         pip install -r requirements_test.txt
  #     - name: Tests suite
  #       run: |
  #         pytest \
  #           --timeout=9 \
  #           --durations=10 \
  #           -n auto \
  #           -p no:sugar \
  #           tests
